Android QR Added
localsend/website pull request #80
Opened 2024-07-09 10:46 UTC by dhiyanesh-cyber

2024-07-09 16:33 UTC, dhiyanesh-cyber commented
@Tienisto I have added QR Codes for android dynamically, Check it out, if there is any issues let me know I'll fix it.

2024-10-30 13:47 UTC, GeckoEidechse requested changes
Adds additional `package-lock.json` and `yarn.lock` while this project uses `pnpm`. Also some unrelated whitespace changes you might wanna get rid of to make the diff nicer to read and faster to review ^^

2024-10-30 13:47 UTC, GeckoEidechse commented on package-lock.json
You might have added this `package-lock.json` by accident.

2024-10-30 13:47 UTC, GeckoEidechse commented on yarn.lock
SSame with `yarn.lock`

2025-06-04 15:32 UTC, closed without merging